---
title: "Unique genes - Biological processes"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r}
library(gprofiler2)
library(ggplot2)
library(ggrepel)

set_base_url("https://biit.cs.ut.ee/gprofiler_archive3/e102_eg49_p15")

enrichment_profile = function(pathways, DEG, color_down, color_up){
  # data is the dataframe containing only significant genes for a specific cell type
  # pathway is a df of pathway ids/go ids that are statistically enriched from geneprofile
  to.plot <- data.frame()
  for(i in 1:nrow(pathways)){
    res = gost(query = pathways[i,"term_id"], organism = "mmusculus")
    gene_set = res$meta$genes_metadata$query$query_1$ensgs
    
    to.plot <- rbind(to.plot,
                     data.frame(
                       Name=pathways[i,"term_name"],
                       mean_FC=c(mean(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange > 0]),
                                 mean(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange < 0])),
                       Type=c("up-regulated","down-regulated"),
                       Set_size = c(length(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange > 0]),
                                    length(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange < 0])),
                       SD=c(sd(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange > 0]),
                            sd(DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange[DEG[DEG$ensembl_gene_id %in% gene_set,]$log2FoldChange < 0]))
                     ))
  }
  
  to.plot[is.nan(to.plot$mean_FC),"mean_FC"] <- 0
  
  p <- ggplot(to.plot, aes(x = mean_FC, y = reorder(Name, abs(mean_FC)), fill = Type, label = Set_size)) + 
    scale_fill_manual(name = "", values = c("down-regulated" = color_down, "up-regulated" = color_up)) + 
    ylab("Biological process") + xlab("Mean logFC") + 
    theme(axis.line = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank()) + theme(text = element_text(size = )) + 
    theme(legend.position = "none") +
    geom_bar(stat = "identity") + geom_text(size = 3.5, position = position_stack(vjust = 0.5)) +
    geom_linerange(aes(xmin=ifelse(mean_FC < 0,mean_FC - SD, mean_FC), xmax=ifelse(mean_FC > 0,mean_FC + SD, mean_FC) ))
  
  return(p)
}

data.folder <- "/workspaces/invitro/invitro/data/"

raw.AT <- read.table(paste0(data.folder,"Hyperoxia_AT.xls"),sep = "\t",header = T,stringsAsFactors = F)
raw.EC <- read.table(paste0(data.folder,"Hyperoxia_EC.xls"),sep = "\t",header = T,stringsAsFactors = F)
raw.MFB <- read.table(paste0(data.folder,"Hyperoxia_MFB.xls"),sep = "\t",header = T,stringsAsFactors = F)

DEG.AT <- raw.AT[which(raw.AT$padj < 0.05),]
DEG.MFB <- raw.MFB[which(raw.MFB$padj < 0.05),]
DEG.EC <- raw.EC[which(raw.EC$padj < 0.05),]

AT.unique <- unique(c(Reduce(intersect,list(DEG.AT$ensembl_gene_id,DEG.EC$ensembl_gene_id)),
               Reduce(intersect,list(DEG.AT$ensembl_gene_id,DEG.MFB$ensembl_gene_id))))

EC.unique <- unique(c(Reduce(intersect,list(DEG.EC$ensembl_gene_id,DEG.AT$ensembl_gene_id)),
                      Reduce(intersect,list(DEG.EC$ensembl_gene_id,DEG.MFB$ensembl_gene_id))))

MFB.unique <- unique(c(Reduce(intersect,list(DEG.MFB$ensembl_gene_id,DEG.AT$ensembl_gene_id)),
                      Reduce(intersect,list(DEG.MFB$ensembl_gene_id,DEG.EC$ensembl_gene_id))))

DEG.AT <- DEG.AT[which(!DEG.AT$ensembl_gene_id %in% AT.unique),]
DEG.EC <- DEG.EC[which(!DEG.EC$ensembl_gene_id %in% EC.unique),]
DEG.MFB <- DEG.MFB[which(!DEG.MFB$ensembl_gene_id %in% MFB.unique),]

AT.gost <- gost(DEG.AT$ensembl_gene_id,organism = "mmusculus",sources=c("GO:MF", "GO:BP","GO:CC", "KEGG"))
AT.BP <- AT.gost$result[AT.gost$result$source == "GO:BP",c("term_id", "source", "term_name", "p_value", "query_size", "term_size", "intersection_size")]

MFB.gost <- gost(DEG.MFB$ensembl_gene_id,organism = "mmusculus",sources=c("GO:MF", "GO:BP","GO:CC", "KEGG"))
MFB.BP <- MFB.gost$result[MFB.gost$result$source == "GO:BP",c("term_id", "source", "term_name", "p_value", "query_size", "term_size", "intersection_size")]
```

# AT

```{r}
enrichment_profile(pathways = AT.BP[1:10,],DEG = DEG.AT,color_down = "#ACD49F",color_up = "#008F00")
```

# FB

```{r}
enrichment_profile(pathways = MFB.BP[1:10,],DEG = DEG.MFB,color_down = "#DF758C",color_up = "#E7298A")
```

# Session info

```{r}
sessionInfo()
```