---
title: "K-means for PCA in the BPD experiment"
author: Juan Henao
date: '`r format(Sys.time(), "%d %B, %Y")`'
description: ""
title-block-banner: "black"
quarto:
  components:
    panel-tabset:
      max_items: 10
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    anchor-sections: true
    number-sections: true
    toc: true
    toc-location: left
    code-fold: true
    theme: cerulean
editor: visual
---

# Amines

```{r}
library(ggplot2)
library(dplyr)

local_file <- "/home/rstudio/project/"

amines <- readRDS(paste0(local_file,"input_data/rds_data/amines.rds"))

set.seed(1234)
amines.model <- kmeans(x = t(amines$abundances), centers = 4)
names(amines.model$cluster) <- colnames(amines$abundances)

if(any(colnames(amines$abundances) != names(amines.model$cluster)|names(amines.model$cluster) != amines$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(amines$abundances))$x

if(any(rownames(pca) != amines$annotation$FullRunName|rownames(pca) != names(amines.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- amines.model$cluster
pca$bpd <- amines$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters), shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(amines$abundances)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(amines$abundances)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) +
  labs(title = "K-means",
       subtitle = "Amines (AM)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "none", plot.title = element_text(size=8))

ggsave(filename = paste0(local_file,"results/BPD/PCA/250707_am_pcs_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Acylcarnitines

```{r}
acyl <- readRDS(paste0(local_file,"input_data/rds_data/acyl.rds"))

set.seed(1234)
acyl.model <- kmeans(x = t(acyl$abundances), centers = 5)
names(acyl.model$cluster) <- colnames(acyl$abundances)

if(any(colnames(acyl$abundances) != names(acyl.model$cluster)|names(acyl.model$cluster) != acyl$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(acyl$abundances))$x

if(any(rownames(pca) != acyl$annotation$FullRunName|rownames(pca) != names(acyl.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- acyl.model$cluster
pca$bpd <- acyl$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters),shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(acyl$abundances)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(acyl$abundances)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#E6AB02")) +
  labs(title = "K-means",
       subtitle = "Acylcarnitines (AC)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "none", plot.title = element_text(size=8))

ggsave(filename = paste0(local_file,"results/BPD/PCA/250707_ac_pcs_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Positive lipids triglycerides

```{r}
pos.tgs <- readRDS(paste0(local_file,"input_data/rds_data/pos_tgs.rds"))

set.seed(1234)
pos.tgs.model <- kmeans(x = t(pos.tgs$abundances), centers = 5)
names(pos.tgs.model$cluster) <- colnames(pos.tgs$abundances)

if(any(colnames(pos.tgs$abundances) != names(pos.tgs.model$cluster)|names(pos.tgs.model$cluster) != pos.tgs$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(pos.tgs$abundances))$x

if(any(rownames(pca) != pos.tgs$annotation$FullRunName|rownames(pca) != names(pos.tgs.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- pos.tgs.model$cluster
pca$bpd <- pos.tgs$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters), shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(pos.tgs$abundances)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(pos.tgs$abundances)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#E6AB02")) +
  labs(title = "K-means",
       subtitle = "Triglycerides (TG)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "none", plot.title = element_text(size=8))

ggsave(filename = paste0(local_file,"results/BPD/PCA/250707_tg_pcs_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Positive lipids non-triglycerides

```{r}
non.pos.tgs <- readRDS(paste0(local_file,"input_data/rds_data/non_pos_tgs.rds"))

set.seed(1234)
non.pos.tgs.model <- kmeans(x = t(non.pos.tgs$abundances), centers = 4)
names(non.pos.tgs.model$cluster) <- colnames(non.pos.tgs$abundances)

if(any(colnames(non.pos.tgs$abundances) != names(non.pos.tgs.model$cluster)|names(non.pos.tgs.model$cluster) != non.pos.tgs$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(non.pos.tgs$abundances))$x

if(any(rownames(pca) != non.pos.tgs$annotation$FullRunName|rownames(pca) != names(non.pos.tgs.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- non.pos.tgs.model$cluster
pca$bpd <- non.pos.tgs$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters), shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(non.pos.tgs$abundances)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(non.pos.tgs$abundances)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) +
  labs(title = "K-means",
       subtitle = "Non-triglycerides (nTG)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "none", plot.title = element_text(size=8))

ggsave(filename = paste0(local_file,"results/BPD/PCA/250707_ntg_pcs_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Proteomics

```{r}
somalogic <- readRDS(paste0(local_file,"input_data/rds_data/proteomics.rds"))

set.seed(1234)
somalogic.model <- kmeans(x = t(somalogic$abundances.corrected), centers = 3)
names(somalogic.model$cluster) <- colnames(somalogic$abundances.corrected)

if(any(colnames(somalogic$abundances.corrected) != names(somalogic.model$cluster)|names(somalogic.model$cluster) != somalogic$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(somalogic$abundances.corrected))$x

if(any(rownames(pca) != somalogic$annotation$FullRunName|rownames(pca) != names(somalogic.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- somalogic.model$cluster
pca$bpd <- somalogic$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters), shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(somalogic$abundances.corrected)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(somalogic$abundances.corrected)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3")) +
  labs(title = "K-means",
       subtitle = "Proteomics (PR)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "none", plot.title = element_text(size=8))

ggsave(filename = paste0(local_file,"results/BPD/PCA/250707_pr_pcs_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Testing labels

::: {.callout-warning}
This plot is to verify the order and nature of labels (e.g., BPD severities and clusters)
**DO NOT EXPORT**
:::

```{r}
pos.tgs <- readRDS(paste0(local_file,"input_data/rds_data/pos_tgs.rds"))

set.seed(1234)
pos.tgs.model <- kmeans(x = t(pos.tgs$abundances), centers = 5)
names(pos.tgs.model$cluster) <- colnames(pos.tgs$abundances)

if(any(colnames(pos.tgs$abundances) != names(pos.tgs.model$cluster)|names(pos.tgs.model$cluster) != pos.tgs$annotation$FullRunName)){stop("clusters, abundances and annotation are unsorted")}

pca <- prcomp(t(pos.tgs$abundances))$x

if(any(rownames(pca) != pos.tgs$annotation$FullRunName|rownames(pca) != names(pos.tgs.model$cluster))){stop("PCA features: annotation, clusters and PCA table are unsorted")}

pca <- pca[,c(1,2)] %>% as.data.frame()
pca$clusters <- pos.tgs.model$cluster
pca$bpd <- pos.tgs$annotation$BPDgrade

p <- ggplot(pca, aes(x=PC1, y=PC2, color=as.factor(clusters), shape = bpd)) + 
  geom_point(size=3) +
  xlab(paste("PC1 (",round(summary(prcomp(t(pos.tgs$abundances)))$importance[2,1]*100,2),"%)")) +
  ylab(paste("PC2 (",round(summary(prcomp(t(pos.tgs$abundances)))$importance[2,2]*100,2),"%)")) +
  scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#E6AB02")) +
  labs(title = "K-means",
       subtitle = "Triglycerides (TG)") +
  theme_classic() + theme(text = element_text(size = 8), legend.position = "right", plot.title = element_text(size=8))

p
```

```{r}
sessionInfo()
```