---
title: "K-means for latent factors scores (BPD experiment)"
author: Juan Henao
date: '`r format(Sys.time(), "%d %B, %Y")`'
description: ""
title-block-banner: "black"
quarto:
  components:
    panel-tabset:
      max_items: 10
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    anchor-sections: true
    number-sections: true
    toc: true
    toc-location: left
    code-fold: true
    theme: cerulean
editor: visual
---

# Basic information

```{r}
library(ggplot2)
library(MOFA2)
library(dplyr)
library(openxlsx)

input_folder <- "/home/rstudio/project/"
dic <- read.table(paste0(input_folder,"input_data/raw_data/230212_proteomics_dictionary.tsv"),sep = "\t",header = TRUE,row.names = 1)
MOFA.object <- readRDS(paste0(input_folder,"input_data/rds_data/MOFA.rds"))
omics <- get_factors(object = MOFA.object,groups = "all",factors = "all") %>% as.data.frame()
clinical <- read.xlsx(xlsxFile = paste0(input_folder,"input_data/raw_data/relevant2MOFA.xlsx"),sheet = 1)
clinical$`D1/BPD.Grad` <- ifelse(clinical$`D1/BPD.Grad` >=2,2,clinical$`D1/BPD.Grad`)
rownames(clinical) <- clinical$PhenoID

factor.explain <- get_variance_explained(MOFA.object)$r2_per_factor$group1
bpd.table <- data.frame(factor = as.factor(rep(c("Factor 1",
                                                 "Factor 2",
                                                 "Factor 3",
                                                 "Factor 4",
                                                 "Factor 5",
                                                 "Factor 6",
                                                 "Factor 7"),5)),
                        value = as.vector(round(factor.explain,2)),
                        view = factor(c(rep("AM",7),
                                           rep("AC",7),
                                           rep("TG",7),
                                           rep("nTG",7),
                                           rep("PR",7)),levels = c("AM","AC","TG","nTG","PR")),
                        group = "")

p <- ggplot(bpd.table,
            aes_string(x="group", y="factor")) + 
  geom_tile(aes_string(fill="value"), color="black") +
  facet_wrap(as.formula(sprintf('~%s',setdiff(c("view", "factor","group"), c("group", "factor", NA)))), nrow=1) +
  labs(x="", y="", title="") + 
  scale_fill_gradientn(colors=c("#f7fcb9","#31a354"), guide="colorbar", limits=c(0,max(bpd.table$value)+0.01)) +
  guides(fill=guide_colorbar("Var. (%)")) +
  theme(
    axis.text.x = element_text(size=rel(1.0), color="black",angle = 45),
    axis.text.y = element_text(size=rel(1.1), color="black"),
    axis.line = element_blank(),
    axis.ticks =  element_blank(),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size=rel(1.0))
  ) + geom_text(aes(label = value), size = 2.5) + theme(text = element_text(size = 8))

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor_scores_a.pdf"),plot = p, width = 3,height = 2.5,units = "in")

p
```

```{r}
q <- ggplot(bpd.table,
            aes_string(x="group", y="factor")) + 
  geom_tile(aes_string(fill="value"), color="black") +
  facet_wrap(as.formula(sprintf('~%s',setdiff(c("view", "factor","group"), c("group", "factor", NA)))), nrow=1) +
  labs(x="", y="", title="") + 
  scale_fill_gradientn(colors=c("#f7fcb9","#31a354"), guide="colorbar", limits=c(0,max(bpd.table$value)+0.01)) +
  guides(fill=guide_colorbar("Var. (%)")) + 
  labs(title = "MOFA - Latent factors",
       subtitle = "Variance explanation") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size=rel(1.0), color="black",angle = 45),
    axis.text.y = element_text(size=rel(1.1), color="black"),
    axis.line = element_blank(),
    axis.ticks =  element_blank(),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size=rel(1.0))
  ) + geom_text(aes(label = value), size = 2.5) + theme(text = element_text(size = 8), plot.title = element_text(size=8))

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor_scores_b.pdf"),plot = q, width = 3,height = 2.5,units = "in")

q
```

# Factor 1

```{r}
set.seed(1234)
f1.model <- kmeans(x = omics[,1], centers = 3)
names(f1.model$cluster) <- rownames(omics)

clinical.f1 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f1 <- clinical.f1[match(MOFA.object@samples_metadata$sample,clinical.f1$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f1.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f1$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f1.model$cluster

p <- plot_factor(object = MOFA.object,factors = 1, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) +
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3")) +
  labs(title = "Clusters",
       subtitle = "Factor 1",) + ylab("Factor scores") +
  theme_bw() + 
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor1_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 2

```{r}
set.seed(1234)
f2.model <- kmeans(x = omics[,2], centers = 4)
names(f2.model$cluster) <- rownames(omics)

clinical.f2 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f2 <- clinical.f2[match(MOFA.object@samples_metadata$sample,clinical.f2$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f2.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f2$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f2.model$cluster

p <- plot_factor(object = MOFA.object,factors = 2, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 2") + theme_bw() +
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor2_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 3

```{r}
set.seed(1234)
f3.model <- kmeans(x = omics[,3], centers = 4)
names(f3.model$cluster) <- rownames(omics)

clinical.f3 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f3 <- clinical.f3[match(MOFA.object@samples_metadata$sample,clinical.f3$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f3.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f3$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f3.model$cluster

p <- plot_factor(object = MOFA.object,factors = 3, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 3") + theme_bw() + 
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor3_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 4

```{r}
set.seed(1234)
f4.model <- kmeans(x = omics[,4], centers = 4)
names(f4.model$cluster) <- rownames(omics)

clinical.f4 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f4 <- clinical.f4[match(MOFA.object@samples_metadata$sample,clinical.f4$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f4.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f4$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f4.model$cluster

p <- plot_factor(object = MOFA.object,factors = 4, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 4") + theme_bw() + 
  ylab("Fator scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor4_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 5

```{r}
set.seed(1234)
f5.model <- kmeans(x = omics[,5], centers = 4)
names(f5.model$cluster) <- rownames(omics)

clinical.f5 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f5 <- clinical.f5[match(MOFA.object@samples_metadata$sample,clinical.f5$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f5.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f5$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f5.model$cluster

p <- plot_factor(object = MOFA.object,factors = 5, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 5") + theme_bw() + 
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor5_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 6

```{r}
set.seed(1234)
f6.model <- kmeans(x = omics[,6], centers = 4)
names(f6.model$cluster) <- rownames(omics)

clinical.f6 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f6 <- clinical.f6[match(MOFA.object@samples_metadata$sample,clinical.f6$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f6.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f6$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f6.model$cluster

p <- plot_factor(object = MOFA.object,factors = 6, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 6") + theme_bw() + 
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor6_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Factor 7

```{r}
set.seed(1234)
f7.model <- kmeans(x = omics[,7], centers = 4)
names(f7.model$cluster) <- rownames(omics)

clinical.f7 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f7 <- clinical.f7[match(MOFA.object@samples_metadata$sample,clinical.f7$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f7.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f7$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f7.model$cluster

p <- plot_factor(object = MOFA.object,factors = 7, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 7") + theme_bw() + 
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "none",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave(filename = paste0(input_folder,"results/BPD/mofa/kmeans/250707_factor7_kmeans.pdf"),plot = p, width = 2.5,height = 2.5,units = "in")

p
```

# Testing labels

::: {.callout-warning}
This plot is to verify the order and nature of labels (e.g., BPD severities and clusters)
**DO NOT EXPORT**
:::

```{r}
set.seed(1234)
f7.model <- kmeans(x = omics[,7], centers = 4)
names(f7.model$cluster) <- rownames(omics)

clinical.f7 <- clinical[which(clinical$PhenoID %in% MOFA.object@samples_metadata$sample),]
clinical.f7 <- clinical.f7[match(MOFA.object@samples_metadata$sample,clinical.f7$PhenoID),]

if(any(MOFA.object@samples_metadata$sample != names(f7.model$cluster)|MOFA.object@samples_metadata$sample != clinical.f7$PhenoID)){stop("clusters and MOFA unsorted")}

MOFA.object@samples_metadata$CLuster <- f7.model$cluster

p <- plot_factor(object = MOFA.object,factors = 7, color_by = MOFA.object@samples_metadata$CLuster, shape_by = "BPDgrade", dot_size = 3, stroke=NA) + 
  scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")) + theme_bw() + 
  labs(title = "Clusters",
       subtitle = "Factor 7") + theme_bw() + 
  ylab("Factor scores") +
  theme(strip.background =element_rect(fill="#4292C6")) + theme(axis.line = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     strip.text.x = element_blank(),
                     legend.position = "right",
                     plot.title = element_text(size=8),
                     text = element_text(size=8)) + theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

p
```

```{r}
sessionInfo()
```