---
title: "PCA plots for BPD individual omics matrices"
author: Juan Henao
date: '`r format(Sys.time(), "%d %B, %Y")`'
description: ""
title-block-banner: "black"
quarto:
  components:
    panel-tabset:
      max_items: 10
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    anchor-sections: true
    number-sections: true
    toc: true
    toc-location: left
    code-fold: true
    theme: cerulean
editor: visual
---

# Amines

```{r}
library(proBatch)
library(ggplot2)

local_file <- "/home/rstudio/project/"

amines <- readRDS(paste0(local_file,"input_data/rds_data/amines.rds"))

p <- plot_PCA(data_matrix = amines$abundances,sample_annotation = amines$annotation,color_by = "BPDgrade") +
  geom_point(size = 3) +
  scale_color_manual(values = c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme(legend.position = "none", text = element_text(size=8), plot.title = element_text(size=8)) + 
  labs(title = "Principal component analysis",
       subtitle = "Amines (AM)")

p
```

# Acylcarnitines

```{r}
acyl <- readRDS(paste0(local_file,"input_data/rds_data/acyl.rds"))

p <- plot_PCA(data_matrix = acyl$abundances,sample_annotation = acyl$annotation,color_by = "BPDgrade") +
  geom_point(size = 3) +
  scale_color_manual(values = c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme(legend.position = "none", text = element_text(size=8), plot.title = element_text(size=8)) + 
  labs(title = "Principal component analysis",
       subtitle = "Acylcarnitines (AC)")

p
```

# Positive lipids triglycerides

```{r}
pos.tgs <- readRDS(paste0(local_file,"input_data/rds_data/pos_tgs.rds"))

p <- plot_PCA(data_matrix = pos.tgs$abundances,sample_annotation = pos.tgs$annotation,color_by = "BPDgrade") +
  geom_point(size = 3) +
  scale_color_manual(values = c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme(legend.position = "none", text = element_text(size=8), plot.title = element_text(size=8)) +
  labs(title = "Principal component analysis",
       subtitle = "Triglycerides (TG)")

p
```

# Positive lipids non-triglycerides

```{r}
non.pos.tgs <- readRDS(paste0(local_file,"input_data/rds_data/non_pos_tgs.rds"))

p <- plot_PCA(data_matrix = non.pos.tgs$abundances,sample_annotation = non.pos.tgs$annotation,color_by = "BPDgrade") +
  geom_point(size = 3) +
  scale_color_manual(values = c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme(legend.position = "none", text = element_text(size=8), plot.title = element_text(size=8)) + 
  labs(title = "Principal component analysis",
       subtitle = "Non-triglycerides (nTG)")

p
```

# Proteomics

```{r}
proteomics <- readRDS(paste0(local_file,"input_data/rds_data/proteomics.rds"))

p <- plot_PCA(data_matrix = proteomics$abundances.corrected,sample_annotation = proteomics$annotation,color_by = "BPDgrade") +
  geom_point(size = 3) +
  scale_color_manual(values = c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme(legend.position = "none", text = element_text(size=8), plot.title = element_text(size=8)) + 
  labs(title = "Principal component analysis",
       subtitle = "Proteomics (PR)")

p
```

```{r}
sessionInfo()
```